[package]
name = "bevy-procedural-world"
version = "0.1.0"
edition = "2021"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.8.1", features = ["dynamic", "jpeg"] }
bevy_flycam = "0.8.1"
bevy_atmosphere = "0.4.1"
#noise = { version = "0.8.2", features = ["images"] }
#bracket-noise = "0.8.7"
noisy_bevy = "0.1.0"
futures-lite = "1.12.0"
bevy_egui = "0.16.1"

# Enable max optimizations for dependencies, but not for our code:
[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 3